import { ActivityLog } from './types';

export const activityLogs: ActivityLog[] = [
  {
    id: 'act1',
    type: 'lead_request',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-12T09:30:00'),
    description: 'Requested lead for Education Services Ltd',
    metadata: {
      clientName: 'Education Services Ltd',
      clientId: 'client6',
    },
  },
  {
    id: 'act2',
    type: 'call_made',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T10:30:00'),
    description: 'Called TechCorp Industries',
    metadata: {
      clientName: 'TechCorp Industries',
      clientId: 'client1',
      duration: 25,
      leadId: 'lead1',
    },
  },
  {
    id: 'act3',
    type: 'meeting_scheduled',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T11:00:00'),
    description: 'Scheduled meeting with TechCorp Industries',
    metadata: {
      clientName: 'TechCorp Industries',
      clientId: 'client1',
      leadId: 'lead1',
    },
  },
  {
    id: 'act4',
    type: 'task_created',
    userId: 'user3',
    userName: 'Mike Wilson',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T10:30:00'),
    description: 'Created task: Prepare IT staffing proposal',
    metadata: {
      taskId: 'task1',
      leadId: 'lead1',
    },
  },
  {
    id: 'act5',
    type: 'task_status_changed',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T14:30:00'),
    description: 'Changed task status from To Do to In Progress',
    metadata: {
      taskId: 'task1',
      oldStatus: 'to_do',
      newStatus: 'in_progress',
    },
  },
  {
    id: 'act6',
    type: 'call_made',
    userId: 'user2',
    userName: 'Sarah Johnson',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-12T14:15:00'),
    description: 'Called Healthcare Solutions Inc',
    metadata: {
      clientName: 'Healthcare Solutions Inc',
      clientId: 'client2',
      duration: 0,
      leadId: 'lead2',
    },
  },
  {
    id: 'act7',
    type: 'comment_added',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T14:30:00'),
    description: 'Added comment on task: Prepare IT staffing proposal',
    metadata: {
      taskId: 'task1',
    },
  },
  {
    id: 'act8',
    type: 'pipeline_moved',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-10T16:00:00'),
    description: 'Moved Manufacturing Global LLC from Follow Up to Proposal Sent',
    metadata: {
      clientName: 'Manufacturing Global LLC',
      clientId: 'client3',
      leadId: 'lead3',
      fromStage: 'follow_up',
      toStage: 'proposal_sent',
    },
  },
  {
    id: 'act9',
    type: 'email_sent',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T15:45:00'),
    description: 'Sent email to rchen@techcorp.com',
    metadata: {
      recipientEmail: 'rchen@techcorp.com',
      clientName: 'TechCorp Industries',
      clientId: 'client1',
    },
  },
  {
    id: 'act10',
    type: 'break_detected',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date(),
    description: 'Coaching break (25 minutes)',
    metadata: {
      duration: 25,
      breakType: 'coaching',
    },
  },
  {
    id: 'act10b',
    type: 'break_detected',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date(),
    description: 'Meeting break (35 minutes)',
    metadata: {
      duration: 35,
      breakType: 'meeting',
    },
  },
  {
    id: 'act11',
    type: 'idle_detected',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date(),
    description: 'Idle time detected (45 minutes)',
    metadata: {
      duration: 45,
    },
  },
  {
    id: 'act12',
    type: 'task_completed',
    userId: 'user4',
    userName: 'Emily Davis',
    subCompanyId: 'sub2',
    timestamp: new Date('2025-10-12T11:00:00'),
    description: 'Completed task: Send candidate profiles',
    metadata: {
      taskId: 'task4',
      leadId: 'lead4',
    },
  },
  {
    id: 'act13',
    type: 'follow_up_created',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T11:15:00'),
    description: 'Created follow-up for TechCorp Industries',
    metadata: {
      clientName: 'TechCorp Industries',
      clientId: 'client1',
      leadId: 'lead1',
    },
  },
  {
    id: 'act14',
    type: 'approval_requested',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T16:45:00'),
    description: 'Requested approval for client contact edit',
    metadata: {
      clientName: 'TechCorp Industries',
      clientId: 'client1',
    },
  },
  {
    id: 'act15',
    type: 'approval_granted',
    userId: 'user3',
    userName: 'Mike Wilson',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-12T14:30:00'),
    description: 'Approved client contact edit',
    metadata: {
      clientName: 'Healthcare Solutions Inc',
      clientId: 'client2',
    },
  },
  {
    id: 'act16',
    type: 'lead_request_rejected',
    userId: 'user3',
    userName: 'Mike Wilson',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-09T10:30:00'),
    description: 'Rejected lead request for Logistics Express Co',
    metadata: {
      clientName: 'Logistics Express Co',
      clientId: 'client8',
      requestedBy: 'John Smith',
    },
  },
  {
    id: 'act17',
    type: 'call_made',
    userId: 'user4',
    userName: 'Emily Davis',
    subCompanyId: 'sub2',
    timestamp: new Date('2025-10-08T11:00:00'),
    description: 'Called Finance Partners Group',
    metadata: {
      clientName: 'Finance Partners Group',
      clientId: 'client4',
      duration: 18,
      leadId: 'lead4',
    },
  },
  {
    id: 'act18',
    type: 'pipeline_moved',
    userId: 'user2',
    userName: 'Sarah Johnson',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-12T10:00:00'),
    description: 'Moved Healthcare Solutions Inc from Contacted to Follow Up',
    metadata: {
      clientName: 'Healthcare Solutions Inc',
      clientId: 'client2',
      leadId: 'lead2',
      fromStage: 'contacted',
      toStage: 'follow_up',
    },
  },
  {
    id: 'act19',
    type: 'lead_request',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-10T14:20:00'),
    description: 'Requested lead for Construction Alliance Inc',
    metadata: {
      clientName: 'Construction Alliance Inc',
      clientId: 'client7',
    },
  },
  {
    id: 'act20',
    type: 'comment_added',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-11T08:15:00'),
    description: 'Added comment on lead request for Construction Alliance Inc',
    metadata: {
      clientName: 'Construction Alliance Inc',
      clientId: 'client7',
    },
  },
  {
    id: 'act21',
    type: 'email_sent',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-10T11:30:00'),
    description: 'Sent proposal email to jpeterson@mfgglobal.com',
    metadata: {
      recipientEmail: 'jpeterson@mfgglobal.com',
      clientName: 'Manufacturing Global LLC',
      clientId: 'client3',
    },
  },
  {
    id: 'act22',
    type: 'task_created',
    userId: 'user3',
    userName: 'Mike Wilson',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-12T15:00:00'),
    description: 'Created task: Follow up with Healthcare Solutions',
    metadata: {
      taskId: 'task2',
      leadId: 'lead2',
    },
  },
  {
    id: 'act23',
    type: 'break_detected',
    userId: 'user2',
    userName: 'Sarah Johnson',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-12T13:00:00'),
    description: 'Started break (45 minutes)',
    metadata: {
      duration: 45,
    },
  },
  {
    id: 'act24',
    type: 'task_completed',
    userId: 'user1',
    userName: 'John Smith',
    subCompanyId: 'sub1',
    timestamp: new Date('2025-10-13T16:00:00'),
    description: 'Completed task: Update CRM with client notes',
    metadata: {
      taskId: 'task5',
    },
  },
];
