import { 
  Client, 
  Lead, 
  Call, 
  FollowUp, 
  Meeting, 
  User, 
  SubCompany,
  ApprovalRequest,
  ClientContact,
  Task,
  LeadRequest,
  ClientNote
} from './types';

export const subCompanies: SubCompany[] = [
  { id: 'sub1', name: 'North Division', mainOrgId: 'main1' },
  { id: 'sub2', name: 'South Division', mainOrgId: 'main1' },
  { id: 'sub3', name: 'East Division', mainOrgId: 'main1' },
];

import { Location } from './types';

export const locations: Location[] = [
  { id: 'loc1', name: 'Toronto Office', address: '123 Bay Street, Toronto, ON', country: 'Canada', isActive: true },
  { id: 'loc2', name: 'Vancouver Office', address: '456 Granville St, Vancouver, BC', country: 'Canada', isActive: true },
  { id: 'loc3', name: 'Lahore Office', address: '789 Mall Road, Lahore, Punjab', country: 'Pakistan', isActive: true },
  { id: 'loc4', name: 'Karachi Office', address: '321 Clifton Rd, Karachi, Sindh', country: 'Pakistan', isActive: true },
];

export const users: User[] = [
  { id: 'user1', firstName: 'John', lastName: 'Smith', name: 'John Smith', email: 'john@na-staffing.com', phone: '555-1001', country: 'Canada', userType: 'Sales Associate', isActive: true, role: 'sales_associate', subCompanyId: 'sub1', locationId: 'loc1', reportingManagerIds: ['user3'], startDate: new Date('2024-01-15') },
  { id: 'user2', firstName: 'Sarah', lastName: 'Johnson', name: 'Sarah Johnson', email: 'sarah@na-staffing.com', phone: '555-1002', country: 'Canada', userType: 'Sales Executive', isActive: true, role: 'sales_associate', subCompanyId: 'sub1', locationId: 'loc1', reportingManagerIds: ['user3'], startDate: new Date('2024-03-01') },
  { id: 'user3', firstName: 'Mike', lastName: 'Wilson', name: 'Mike Wilson', email: 'mike@na-staffing.com', phone: '555-1003', country: 'Canada', userType: 'Sales Manager', isActive: true, role: 'sales_manager', subCompanyId: 'sub1', locationId: 'loc1', reportingManagerIds: ['user5'], accessibleLocationIds: ['loc1', 'loc2'], startDate: new Date('2023-06-10') },
  { id: 'user4', firstName: 'Emily', lastName: 'Davis', name: 'Emily Davis', email: 'emily@na-staffing.com', phone: '555-1004', country: 'Pakistan', userType: 'Sales Manager', isActive: true, role: 'sales_manager', subCompanyId: 'sub2', locationId: 'loc3', reportingManagerIds: ['user5'], accessibleLocationIds: ['loc3', 'loc4'], startDate: new Date('2023-09-20') },
  { id: 'user5', firstName: 'Robert', lastName: 'Taylor', name: 'Robert Taylor', email: 'robert@na-staffing.com', phone: '555-1005', country: 'Canada', userType: 'Director', isActive: true, role: 'director', subCompanyId: 'sub1', locationId: 'loc1', reportingManagerIds: [], startDate: new Date('2022-01-05') },
  { id: 'user6', firstName: 'Admin', lastName: 'User', name: 'Admin User', email: 'admin@na-staffing.com', phone: '555-1006', country: 'Canada', userType: 'IT', isActive: true, role: 'it', subCompanyId: 'sub1', locationId: 'loc1', reportingManagerIds: [], startDate: new Date('2022-05-15') },
  { id: 'user7', firstName: 'Ali', lastName: 'Khan', name: 'Ali Khan', email: 'ali@na-staffing.com', phone: '555-1007', country: 'Pakistan', userType: 'Sales Associate', isActive: true, role: 'sales_associate', subCompanyId: 'sub2', locationId: 'loc3', reportingManagerIds: ['user4'], startDate: new Date('2024-02-01') },
];

export const clients: Client[] = [
  {
    id: 'client1',
    name: 'TechCorp Industries',
    industry: 'Technology',
    location: 'Toronto, ON',
    address: '123 Bay Street, Suite 200, Toronto, ON M5J 2N8',
    companySize: '500-1000 employees',
    tags: ['VIP', 'High Volume', 'Strategic Partner'],
    status: 'active',
    lastActivity: new Date('2025-10-13'),
    createdAt: new Date('2025-01-15'),
    notes: [
      {
        id: 'note1',
        clientId: 'client1',
        userId: 'user3',
        userName: 'Mike Wilson',
        userRole: 'sales_manager',
        content: 'Key strategic account - requires white glove service. Executive relationship established with CEO.',
        isPublic: true,
        isPinned: true,
        createdAt: new Date('2025-09-15'),
      },
      {
        id: 'note2',
        clientId: 'client1',
        userId: 'user3',
        userName: 'Mike Wilson',
        userRole: 'sales_manager',
        content: 'Internal note: Budget approval pending for Q1. Do not push aggressively until confirmed.',
        isPublic: false,
        isPinned: true,
        createdAt: new Date('2025-10-01'),
      },
      {
        id: 'note3',
        clientId: 'client1',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'Had a great call with Robert Chen. He mentioned they are expanding their tech team in Q2.',
        isPublic: true,
        isPinned: true,
        createdAt: new Date('2025-10-05'),
      },
      {
        id: 'note4',
        clientId: 'client1',
        userId: 'user2',
        userName: 'Sarah Johnson',
        userRole: 'sales_associate',
        content: 'Followed up on the proposal. They are comparing with two other vendors.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-10-08'),
      },
      {
        id: 'note5',
        clientId: 'client1',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'Client prefers morning meetings, typically available between 9-11 AM.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-10-10'),
      },
      {
        id: 'note6',
        clientId: 'client1',
        userId: 'user4',
        userName: 'Emily Davis',
        userRole: 'operations_manager',
        content: 'Pricing approved at 15% discount for volume commitment. Valid until end of Q4.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-10-12'),
      },
    ],
    contacts: [
      {
        id: 'contact1',
        clientId: 'client1',
        name: 'Robert Chen',
        title: 'HR Director',
        email: 'rchen@techcorp.com',
        phone: '555-0101',
        isPrimary: true,
      },
      {
        id: 'contact2',
        clientId: 'client1',
        name: 'Lisa Martinez',
        title: 'Recruitment Manager',
        email: 'lmartinez@techcorp.com',
        phone: '555-0102',
        isPrimary: false,
        isUnsubscribed: true,
      }
    ],
  },
  {
    id: 'client2',
    name: 'Healthcare Solutions Inc',
    industry: 'Healthcare',
    location: 'Vancouver, BC',
    address: '789 Innovation Drive, Vancouver, BC V6B 4Y8',
    companySize: '1000-5000 employees',
    tags: [],
    status: 'active',
    lastActivity: new Date('2025-10-12'),
    createdAt: new Date('2025-02-20'),
    notes: [
      {
        id: 'note7',
        clientId: 'client2',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'Initial outreach completed. Dr. White is interested in discussing staffing needs for new clinic.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-10-11'),
      },
    ],
    contacts: [
      {
        id: 'contact3',
        clientId: 'client2',
        name: 'Dr. Amanda White',
        title: 'Chief Operations Officer',
        email: 'awhite@healthsolutions.com',
        phone: '555-0201',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client3',
    name: 'Manufacturing Global LLC',
    industry: 'Manufacturing',
    location: 'Montreal, QC',
    address: '456 René-Lévesque Blvd, Montreal, QC H3B 4W5',
    companySize: '100-500 employees',
    tags: ['High Volume', 'Seasonal'],
    status: 'active',
    lastActivity: new Date('2025-10-10'),
    createdAt: new Date('2025-03-10'),
    notes: [
      {
        id: 'note8',
        clientId: 'client3',
        userId: 'user3',
        userName: 'Mike Wilson',
        userRole: 'sales_manager',
        content: 'Seasonal client - ramp up hiring in spring and fall. Plan outreach 6 weeks ahead.',
        isPublic: true,
        isPinned: true,
        createdAt: new Date('2025-08-15'),
      },
      {
        id: 'note9',
        clientId: 'client3',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'James mentioned they need 20+ temp workers for the holiday season.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-09-20'),
      },
      {
        id: 'note10',
        clientId: 'client3',
        userId: 'user2',
        userName: 'Sarah Johnson',
        userRole: 'sales_associate',
        content: 'Follow up scheduled for next week regarding the temp worker order.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-10-05'),
      },
    ],
    contacts: [
      {
        id: 'contact4',
        clientId: 'client3',
        name: 'James Peterson',
        title: 'VP of Operations',
        email: 'jpeterson@mfgglobal.com',
        phone: '555-0301',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client4',
    name: 'Finance Partners Group',
    industry: 'Finance',
    location: 'Calgary, AB',
    address: '1000 9th Avenue SW, Floor 42, Calgary, AB T2P 5N3',
    companySize: '5000+ employees',
    tags: [],
    status: 'lost',
    lastActivity: new Date('2025-10-08'),
    createdAt: new Date('2025-04-05'),
    notes: [
      {
        id: 'note11',
        clientId: 'client4',
        userId: 'user3',
        userName: 'Mike Wilson',
        userRole: 'sales_manager',
        content: 'Lost to competitor on pricing. Consider revisiting in Q2 next year.',
        isPublic: true,
        isPinned: true,
        createdAt: new Date('2025-10-01'),
      },
      {
        id: 'note12',
        clientId: 'client4',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'Rachel mentioned they signed a 2-year contract with the other vendor.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-09-28'),
      },
    ],
    contacts: [
      {
        id: 'contact5',
        clientId: 'client4',
        name: 'Rachel Goldman',
        title: 'Talent Acquisition Lead',
        email: 'rgoldman@financepartners.com',
        phone: '555-0401',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client5',
    name: 'Retail Dynamics Corp',
    industry: 'Retail',
    location: 'Ottawa, ON',
    address: '555 Wellington Street, Ottawa, ON K1A 0A6',
    companySize: '100-500 employees',
    tags: [],
    status: 'ex',
    lastActivity: new Date('2025-09-30'),
    createdAt: new Date('2025-05-15'),
    notes: [
      {
        id: 'note13',
        clientId: 'client5',
        userId: 'user4',
        userName: 'Emily Davis',
        userRole: 'operations_manager',
        content: 'Client paused services due to budget cuts. Good relationship - worth re-engaging next fiscal year.',
        isPublic: true,
        isPinned: true,
        createdAt: new Date('2025-09-15'),
      },
      {
        id: 'note14',
        clientId: 'client5',
        userId: 'user2',
        userName: 'Sarah Johnson',
        userRole: 'sales_associate',
        content: 'Kevin was happy with our service, just internal budget issues.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-09-10'),
      },
    ],
    contacts: [
      {
        id: 'contact6',
        clientId: 'client5',
        name: 'Kevin Brown',
        title: 'Store Operations Manager',
        email: 'kbrown@retaildynamics.com',
        phone: '555-0501',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client6',
    name: 'Education Services Ltd',
    industry: 'Education',
    location: 'Edmonton, AB',
    address: '222 Jasper Avenue, Edmonton, AB T5J 1K8',
    companySize: '50-100 employees',
    tags: [],
    status: 'contacted',
    lastActivity: new Date('2025-09-25'),
    createdAt: new Date('2025-06-10'),
    notes: [
      {
        id: 'note15',
        clientId: 'client6',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'Susan is interested but needs approval from their board. Waiting for next month.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-09-20'),
      },
      {
        id: 'note16',
        clientId: 'client6',
        userId: 'user2',
        userName: 'Sarah Johnson',
        userRole: 'sales_associate',
        content: 'Sent over our education sector case studies as requested.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-09-22'),
      },
    ],
    contacts: [
      {
        id: 'contact7',
        clientId: 'client6',
        name: 'Susan Miller',
        title: 'HR Coordinator',
        email: 'smiller@eduservices.com',
        phone: '555-0601',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client7',
    name: 'Construction Alliance Inc',
    industry: 'Construction',
    location: 'Winnipeg, MB',
    address: '888 Portage Avenue, Winnipeg, MB R3C 0C1',
    companySize: '500-1000 employees',
    tags: [],
    status: 'unsubscribed',
    lastActivity: new Date('2025-09-20'),
    createdAt: new Date('2025-07-01'),
    notes: [],
    contacts: [
      {
        id: 'contact8',
        clientId: 'client7',
        name: 'Tom Anderson',
        title: 'Project Director',
        email: 'tanderson@constructionalliance.com',
        phone: '555-0701',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client8',
    name: 'Logistics Express Co',
    industry: 'Logistics',
    location: 'Halifax, NS',
    address: '333 Barrington Street, Halifax, NS B3J 1L1',
    companySize: '100-500 employees',
    tags: [],
    status: 'active',
    lastActivity: new Date('2025-09-15'),
    createdAt: new Date('2025-08-05'),
    notes: [
      {
        id: 'note17',
        clientId: 'client8',
        userId: 'user3',
        userName: 'Mike Wilson',
        userRole: 'sales_manager',
        content: 'Growing account - potential for long-term contract. Prioritize relationship building.',
        isPublic: true,
        isPinned: true,
        createdAt: new Date('2025-08-20'),
      },
      {
        id: 'note18',
        clientId: 'client8',
        userId: 'user3',
        userName: 'Mike Wilson',
        userRole: 'sales_manager',
        content: 'Internal: Watch margin on this account, they negotiate hard.',
        isPublic: false,
        isPinned: false,
        createdAt: new Date('2025-09-01'),
      },
      {
        id: 'note19',
        clientId: 'client8',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'Maria prefers email communication over calls.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-09-10'),
      },
    ],
    contacts: [
      {
        id: 'contact9',
        clientId: 'client8',
        name: 'Maria Garcia',
        title: 'Operations Manager',
        email: 'mgarcia@logisticsexpress.com',
        phone: '555-0801',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client9',
    name: 'Banking Solutions Ltd',
    industry: 'Banking',
    location: 'Quebec City, QC',
    address: '777 Grande Allée Est, Quebec City, QC G1R 2J5',
    companySize: '1000-5000 employees',
    tags: [],
    status: 'contacted',
    lastActivity: new Date('2025-10-11'),
    createdAt: new Date('2025-01-20'),
    notes: [
      {
        id: 'note20',
        clientId: 'client9',
        userId: 'user2',
        userName: 'Sarah Johnson',
        userRole: 'sales_associate',
        content: 'David is the key decision maker. Very responsive to data-driven presentations.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-10-08'),
      },
      {
        id: 'note21',
        clientId: 'client9',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'They have strict compliance requirements - need to prepare documentation.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-10-10'),
      },
    ],
    contacts: [
      {
        id: 'contact10',
        clientId: 'client9',
        name: 'David Thompson',
        title: 'HR Director',
        email: 'dthompson@bankingsolutions.com',
        phone: '555-0901',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client10',
    name: 'Energy Corp International',
    industry: 'Energy',
    location: 'Regina, SK',
    address: '999 Albert Street, Regina, SK S4P 2P1',
    companySize: '5000+ employees',
    tags: [],
    status: 'active',
    lastActivity: new Date('2025-10-09'),
    createdAt: new Date('2025-03-15'),
    notes: [
      {
        id: 'note22',
        clientId: 'client10',
        userId: 'user4',
        userName: 'Emily Davis',
        userRole: 'operations_manager',
        content: 'Major enterprise client. Quarterly business reviews required.',
        isPublic: true,
        isPinned: true,
        createdAt: new Date('2025-06-01'),
      },
      {
        id: 'note23',
        clientId: 'client10',
        userId: 'user1',
        userName: 'John Smith',
        userRole: 'sales_associate',
        content: 'Patricia mentioned upcoming expansion project in Saskatchewan.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-09-25'),
      },
      {
        id: 'note24',
        clientId: 'client10',
        userId: 'user2',
        userName: 'Sarah Johnson',
        userRole: 'sales_associate',
        content: 'Set up introduction meeting with their new regional manager.',
        isPublic: true,
        isPinned: false,
        createdAt: new Date('2025-10-05'),
      },
    ],
    contacts: [
      {
        id: 'contact11',
        clientId: 'client10',
        name: 'Patricia Lewis',
        title: 'Chief People Officer',
        email: 'plewis@energycorp.com',
        phone: '555-1001',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client11',
    name: 'MediaWorks Studios',
    industry: 'Media & Entertainment',
    location: 'Toronto, ON',
    address: '444 King Street West, Toronto, ON M5V 1L7',
    companySize: '500-1000 employees',
    tags: ['Project-Based'],
    status: 'active',
    lastActivity: new Date('2025-10-07'),
    createdAt: new Date('2025-04-20'),
    notes: [],
    contacts: [
      {
        id: 'contact12',
        clientId: 'client11',
        name: 'Jennifer Rodriguez',
        title: 'Production Manager',
        email: 'jrodriguez@mediaworks.com',
        phone: '555-1101',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client12',
    name: 'Global Retail Ventures',
    industry: 'Retail',
    location: 'Mississauga, ON',
    address: '555 City Centre Drive, Mississauga, ON L5B 2C9',
    companySize: '1000-5000 employees',
    tags: ['Permanently Closed'],
    status: 'permanently_closed',
    lastActivity: new Date('2025-08-15'),
    createdAt: new Date('2024-11-10'),
    notes: [],
    contacts: [
      {
        id: 'contact13',
        clientId: 'client12',
        name: 'Michael Carter',
        title: 'Former VP Operations',
        email: 'mcarter@globalretail.com',
        phone: '555-1201',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client13',
    name: 'Pacific Insurance Group',
    industry: 'Insurance',
    location: 'Victoria, BC',
    address: '222 Government Street, Victoria, BC V8V 2L2',
    companySize: '500-1000 employees',
    tags: [],
    status: 'active',
    lastActivity: new Date('2025-10-14'),
    createdAt: new Date('2025-09-01'),
    notes: [],
    contacts: [
      {
        id: 'contact14',
        clientId: 'client13',
        name: 'Brian Foster',
        title: 'Talent Acquisition',
        email: 'bfoster@pacificinsurance.com',
        phone: '555-1301',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client14',
    name: 'Automotive Solutions Inc',
    industry: 'Automotive',
    location: 'Windsor, ON',
    address: '888 Riverside Drive East, Windsor, ON N9A 5K4',
    companySize: '1000-5000 employees',
    tags: ['High Volume'],
    status: 'contacted',
    lastActivity: new Date('2025-10-13'),
    createdAt: new Date('2025-02-10'),
    notes: [],
    contacts: [
      {
        id: 'contact15',
        clientId: 'client14',
        name: 'Karen Walsh',
        title: 'Hiring Manager',
        email: 'kwalsh@autosolutions.com',
        phone: '555-1401',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client15',
    name: 'TechStart Innovations',
    industry: 'Technology',
    location: 'Kelowna, BC',
    address: '555 Water Street, Kelowna, BC V1Y 9P8',
    companySize: '50-100 employees',
    tags: [],
    status: 'active',
    lastActivity: new Date('2025-10-12'),
    createdAt: new Date('2025-09-20'),
    notes: [],
    contacts: [
      {
        id: 'contact16',
        clientId: 'client15',
        name: 'Alex Kumar',
        title: 'Co-Founder',
        email: 'akumar@techstart.com',
        phone: '555-1501',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client16',
    name: 'Hospitality Partners LLC',
    industry: 'Hospitality',
    location: 'Banff, AB',
    address: '777 Banff Avenue, Banff, AB T1L 1A1',
    companySize: '500-1000 employees',
    tags: ['Seasonal'],
    status: 'contacted',
    lastActivity: new Date('2025-10-11'),
    createdAt: new Date('2025-01-05'),
    notes: [],
    contacts: [
      {
        id: 'contact17',
        clientId: 'client16',
        name: 'Carlos Mendez',
        title: 'Regional Manager',
        email: 'cmendez@hospitalitypartners.com',
        phone: '555-1601',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client17',
    name: 'Pharma Research Labs',
    industry: 'Pharmaceutical',
    location: 'Kitchener, ON',
    address: '333 King Street East, Kitchener, ON N2G 2K8',
    companySize: '100-500 employees',
    tags: [],
    status: 'active',
    lastActivity: new Date('2025-10-10'),
    createdAt: new Date('2025-08-15'),
    notes: [],
    contacts: [
      {
        id: 'contact18',
        clientId: 'client17',
        name: 'Dr. Sarah Kim',
        title: 'HR Director',
        email: 'skim@pharmaresearch.com',
        phone: '555-1701',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client18',
    name: 'Green Energy Solutions',
    industry: 'Renewable Energy',
    location: 'Jasper, AB',
    address: '999 Connaught Drive, Jasper, AB T0E 1E0',
    companySize: '100-500 employees',
    tags: [],
    status: 'active',
    lastActivity: new Date('2025-10-09'),
    createdAt: new Date('2025-06-20'),
    notes: [],
    contacts: [
      {
        id: 'contact19',
        clientId: 'client18',
        name: 'Emma Watson',
        title: 'Operations Lead',
        email: 'ewatson@greenenergy.com',
        phone: '555-1801',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client19',
    name: 'Legal Associates Group',
    industry: 'Legal Services',
    location: 'Hamilton, ON',
    address: '444 James Street North, Hamilton, ON L8R 2K3',
    companySize: '50-100 employees',
    tags: [],
    status: 'lost',
    lastActivity: new Date('2025-09-28'),
    createdAt: new Date('2025-07-10'),
    notes: [],
    contacts: [
      {
        id: 'contact20',
        clientId: 'client19',
        name: 'Richard Stone',
        title: 'Managing Partner',
        email: 'rstone@legalassociates.com',
        phone: '555-1901',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client20',
    name: 'Food Distribution Co',
    industry: 'Food & Beverage',
    location: 'Sudbury, ON',
    address: '666 Big Nickel Drive, Sudbury, ON P3E 4X9',
    companySize: '500-1000 employees',
    tags: [],
    status: 'permanently_closed',
    lastActivity: new Date('2025-10-08'),
    createdAt: new Date('2025-09-25'),
    notes: [],
    contacts: [
      {
        id: 'contact21',
        clientId: 'client20',
        name: 'Lisa Chang',
        title: 'Supply Chain Manager',
        email: 'lchang@fooddistribution.com',
        phone: '555-2001',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client21',
    name: 'Digital Marketing Pro',
    industry: 'Marketing',
    location: 'Charlottetown, PE',
    address: '123 Queen Street, Charlottetown, PE C1A 4A9',
    companySize: '50-100 employees',
    tags: [],
    status: 'active',
    lastActivity: new Date('2025-10-07'),
    createdAt: new Date('2025-08-01'),
    notes: [],
    contacts: [
      {
        id: 'contact22',
        clientId: 'client21',
        name: 'Tyler Brooks',
        title: 'CEO',
        email: 'tbrooks@digitalmarketingpro.com',
        phone: '555-2101',
        isPrimary: true,
      }
    ],
  },
  {
    id: 'client22',
    name: 'Aerospace Engineering Corp',
    industry: 'Aerospace',
    location: 'Montreal, QC',
    address: '777 Boulevard Décarie, Montreal, QC H4A 3J8',
    companySize: '5000+ employees',
    tags: ['VIP', 'Strategic Partner'],
    status: 'active',
    lastActivity: new Date('2025-10-06'),
    createdAt: new Date('2025-03-01'),
    notes: [],
    contacts: [
      {
        id: 'contact23',
        clientId: 'client22',
        name: 'Colonel James Mitchell',
        title: 'HR Operations Director',
        email: 'jmitchell@aerocorp.com',
        phone: '555-2201',
        isPrimary: true,
      }
    ],
  },
];

export const leads: Lead[] = [
  {
    id: 'lead1',
    clientId: 'client1',
    ownerId: 'user1',
    ownerName: 'John Smith',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'meeting_scheduled',
    status: 'open',
    temperature: 'hot',
    value: 50000,
    lastActivity: new Date('2025-10-13'),
    nextFollowUp: new Date('2025-10-15'),
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-10-13'),
    notes: 'Strong interest in temporary IT staff for Q1 2026',
  },
  {
    id: 'lead2',
    clientId: 'client2',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'follow_up',
    status: 'open',
    temperature: 'hot',
    value: 75000,
    lastActivity: new Date('2025-10-12'),
    nextFollowUp: new Date('2025-10-14'),
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-10-12'),
    notes: 'Need nursing staff for new facility opening',
  },
  {
    id: 'lead3',
    clientId: 'client3',
    ownerId: 'user1',
    ownerName: 'John Smith',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'proposal_sent',
    status: 'open',
    temperature: 'warm',
    value: 120000,
    lastActivity: new Date('2025-10-10'),
    nextFollowUp: new Date('2025-10-16'),
    createdAt: new Date('2025-08-20'),
    updatedAt: new Date('2025-10-10'),
    notes: 'Proposal sent for warehouse staffing solution',
    proposalData: {
      locationType: 'single',
      selectedClients: [],
      agreementTypes: ['temp'],
      tempPricing: {
        pricingType: 'markup',
        pricingValue: 35,
        minimumHours: 480,
      },
      paymentTerms: 'net_30',
      comment: 'Comprehensive warehouse staffing proposal including forklift operators, packers, and shift supervisors. Proposed 3-month contract with option to extend.',
      attachments: [
        { id: 'att1', name: 'Warehouse_Staffing_Proposal.pdf', size: 245678, type: 'application/pdf', url: '#' },
        { id: 'att2', name: 'Pricing_Schedule.xlsx', size: 45230, type: 'application/vnd.ms-excel', url: '#' },
      ],
      createdAt: new Date('2025-10-10'),
    },
  },
  {
    id: 'lead4',
    clientId: 'client4',
    ownerId: 'user4',
    ownerName: 'Emily Davis',
    subCompanyId: 'sub2',
    subCompanyName: 'South Division',
    stage: 'follow_up',
    status: 'open',
    temperature: 'warm',
    value: 35000,
    lastActivity: new Date('2025-10-08'),
    nextFollowUp: new Date('2025-10-14'),
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-08'),
    notes: 'Initial contact made, discussing accounting temp needs',
  },
  {
    id: 'lead8',
    clientId: 'client8',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'follow_up',
    status: 'open',
    temperature: 'warm',
    value: 45000,
    lastActivity: new Date('2025-09-15'),
    nextFollowUp: new Date('2025-10-20'),
    createdAt: new Date('2025-08-05'),
    updatedAt: new Date('2025-09-15'),
    notes: 'Logistics staffing for distribution center',
  },
  {
    id: 'lead10',
    clientId: 'client10',
    ownerId: 'user1',
    ownerName: 'John Smith',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'meeting_scheduled',
    status: 'open',
    temperature: 'hot',
    value: 200000,
    lastActivity: new Date('2025-10-09'),
    nextFollowUp: new Date('2025-10-18'),
    createdAt: new Date('2025-03-15'),
    updatedAt: new Date('2025-10-09'),
    notes: 'Major energy project staffing needs',
  },
  {
    id: 'lead11',
    clientId: 'client11',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'proposal_sent',
    status: 'open',
    temperature: 'warm',
    value: 80000,
    lastActivity: new Date('2025-10-07'),
    nextFollowUp: new Date('2025-10-19'),
    createdAt: new Date('2025-04-20'),
    updatedAt: new Date('2025-10-07'),
    notes: 'Production crew staffing for upcoming projects',
    proposalData: {
      locationType: 'multiple',
      selectedClients: ['client12', 'client13'],
      agreementTypes: ['temp'],
      tempPricing: {
        pricingType: 'bill_rate',
        pricingValue: 45,
        minimumHours: 480,
      },
      paymentTerms: 'net_15',
      comment: 'Multi-location production staffing proposal covering 3 facilities. Includes camera operators, lighting technicians, and production assistants.',
      attachments: [
        { id: 'att3', name: 'Production_Crew_Proposal.pdf', size: 512345, type: 'application/pdf', url: '#' },
      ],
      createdAt: new Date('2025-10-07'),
    },
  },
  {
    id: 'lead13',
    clientId: 'client13',
    ownerId: 'user1',
    ownerName: 'John Smith',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'follow_up',
    status: 'open',
    temperature: 'hot',
    value: 95000,
    lastActivity: new Date('2025-10-14'),
    nextFollowUp: new Date('2025-10-21'),
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-10-14'),
    notes: 'Insurance claims processing staff needed',
  },
  {
    id: 'lead15',
    clientId: 'client15',
    ownerId: 'user4',
    ownerName: 'Emily Davis',
    subCompanyId: 'sub2',
    subCompanyName: 'South Division',
    stage: 'meeting_scheduled',
    status: 'open',
    temperature: 'warm',
    value: 25000,
    lastActivity: new Date('2025-10-12'),
    nextFollowUp: new Date('2025-10-22'),
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2025-10-12'),
    notes: 'Tech startup looking for dev contractors',
  },
  {
    id: 'lead17',
    clientId: 'client17',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'follow_up',
    status: 'open',
    temperature: 'warm',
    value: 65000,
    lastActivity: new Date('2025-10-10'),
    nextFollowUp: new Date('2025-10-23'),
    createdAt: new Date('2025-08-15'),
    updatedAt: new Date('2025-10-10'),
    notes: 'Lab technician staffing requirements',
  },
  {
    id: 'lead18',
    clientId: 'client18',
    ownerId: 'user1',
    ownerName: 'John Smith',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'proposal_sent',
    status: 'open',
    temperature: 'hot',
    value: 110000,
    lastActivity: new Date('2025-10-09'),
    nextFollowUp: new Date('2025-10-24'),
    createdAt: new Date('2025-06-20'),
    updatedAt: new Date('2025-10-09'),
    notes: 'Renewable energy technicians for new solar farm',
    proposalData: {
      locationType: 'single',
      selectedClients: [],
      agreementTypes: ['direct_placement'],
      directPricing: {
        pricingType: 'markup',
        pricingValue: 28,
      },
      paymentTerms: 'net_45',
      comment: 'Solar farm technician staffing proposal. 15 certified solar panel installers and 5 electrical engineers needed for 6-month project.',
      attachments: [
        { id: 'att4', name: 'Solar_Technician_Proposal.pdf', size: 389000, type: 'application/pdf', url: '#' },
        { id: 'att5', name: 'Certifications_Required.docx', size: 67890, type: 'application/msword', url: '#' },
        { id: 'att6', name: 'Project_Timeline.pdf', size: 156780, type: 'application/pdf', url: '#' },
      ],
      createdAt: new Date('2025-10-09'),
    },
  },
  {
    id: 'lead21',
    clientId: 'client21',
    ownerId: 'user4',
    ownerName: 'Emily Davis',
    subCompanyId: 'sub2',
    subCompanyName: 'South Division',
    stage: 'meeting_scheduled',
    status: 'open',
    temperature: 'warm',
    value: 30000,
    lastActivity: new Date('2025-10-07'),
    nextFollowUp: new Date('2025-10-25'),
    createdAt: new Date('2025-08-01'),
    updatedAt: new Date('2025-10-07'),
    notes: 'Marketing team expansion needs',
  },
  {
    id: 'lead22',
    clientId: 'client22',
    ownerId: 'user1',
    ownerName: 'John Smith',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'follow_up',
    status: 'open',
    temperature: 'hot',
    value: 350000,
    lastActivity: new Date('2025-10-06'),
    nextFollowUp: new Date('2025-10-26'),
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-10-06'),
    notes: 'Large aerospace engineering contract',
  },
  {
    id: 'lead19',
    clientId: 'client19',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    stage: 'new_lead',
    status: 'closed_lost',
    temperature: 'cold',
    lastActivity: new Date('2025-09-28'),
    createdAt: new Date('2025-07-10'),
    updatedAt: new Date('2025-09-28'),
    notes: 'Lost - went with competitor',
  },
];

export const calls: Call[] = [
  {
    id: 'call1',
    clientId: 'client1',
    leadId: 'lead1',
    ownerId: 'user1',
    ownerName: 'John Smith',
    outcome: 'answered',
    duration: 25,
    notes: 'Discussed IT staffing needs. Meeting scheduled for next week.',
    timestamp: new Date('2025-10-13T10:30:00'),
  },
  {
    id: 'call2',
    clientId: 'client2',
    leadId: 'lead2',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    outcome: 'voicemail',
    notes: 'Left voicemail about nursing staff availability',
    timestamp: new Date('2025-10-12T14:15:00'),
  },
  {
    id: 'call3',
    clientId: 'client4',
    leadId: 'lead4',
    ownerId: 'user4',
    ownerName: 'Emily Davis',
    outcome: 'answered',
    duration: 18,
    notes: 'Good conversation about temporary accounting needs for year-end',
    timestamp: new Date('2025-10-08T11:00:00'),
  },
];

export const followUps: FollowUp[] = [
  {
    id: 'followup1',
    clientId: 'client1',
    leadId: 'lead1',
    contactId: 'contact1',
    ownerId: 'user1',
    ownerName: 'John Smith',
    dueDate: new Date('2025-10-15T09:00:00'),
    notes: 'Send meeting agenda and prepare staffing proposal',
    completed: false,
    createdAt: new Date('2025-10-13'),
    comments: [],
  },
  {
    id: 'followup2',
    clientId: 'client2',
    leadId: 'lead2',
    contactId: 'contact3',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    dueDate: new Date('2025-10-14T10:00:00'),
    notes: 'Follow up on voicemail - discuss nursing availability',
    completed: false,
    createdAt: new Date('2025-10-12'),
    comments: [],
  },
  {
    id: 'followup3',
    clientId: 'client3',
    leadId: 'lead3',
    contactId: 'contact4',
    ownerId: 'user1',
    ownerName: 'John Smith',
    dueDate: new Date('2025-10-16T14:00:00'),
    notes: 'Check on proposal review status',
    completed: false,
    createdAt: new Date('2025-10-10'),
    comments: [],
  },
  {
    id: 'followup4',
    clientId: 'client4',
    leadId: 'lead4',
    contactId: 'contact5',
    ownerId: 'user4',
    ownerName: 'Emily Davis',
    dueDate: new Date('2025-10-11T15:00:00'),
    notes: 'Send additional accounting candidate profiles',
    completed: true,
    outcome: 'next_follow_up',
    completedAt: new Date('2025-10-11T16:30:00'),
    createdAt: new Date('2025-10-08'),
    comments: [],
  },
];

export const meetings: Meeting[] = [
  {
    id: 'meeting1',
    clientId: 'client1',
    leadId: 'lead1',
    ownerId: 'user1',
    ownerName: 'John Smith',
    title: 'IT Staffing Requirements Discussion',
    startTime: new Date('2025-10-16T14:00:00'),
    endTime: new Date('2025-10-16T15:00:00'),
    meetingLink: 'https://meet.example.com/it-staffing-techcorp',
    agenda: 'Review IT staffing needs for Q1 2026, discuss candidate profiles, pricing',
    attendees: ['Robert Chen', 'Lisa Martinez'],
    createdAt: new Date('2025-10-13'),
  },
  {
    id: 'meeting2',
    clientId: 'client3',
    leadId: 'lead3',
    ownerId: 'user1',
    ownerName: 'John Smith',
    title: 'Proposal Review Meeting',
    startTime: new Date('2025-10-14T10:00:00'),
    endTime: new Date('2025-10-14T11:00:00'),
    location: 'Manufacturing Global LLC HQ',
    agenda: 'Review warehouse staffing proposal, answer questions, negotiate terms',
    attendees: ['James Peterson'],
    notes: 'Client very interested, some concerns about pricing',
    createdAt: new Date('2025-10-10'),
  },
];

export const approvalRequests: ApprovalRequest[] = [
  {
    id: 'approval1',
    type: 'client_contact_edit',
    requestedBy: 'user1',
    requestedByName: 'John Smith',
    requestedAt: new Date('2025-10-13T16:45:00'),
    status: 'pending',
    changes: [
      {
        field: 'email',
        oldValue: 'rchen@techcorp.com',
        newValue: 'robert.chen@techcorp.com',
      },
      {
        field: 'phone',
        oldValue: '555-0101',
        newValue: '555-0199',
      }
    ],
    resourceId: 'contact1',
  },
  {
    id: 'approval2',
    type: 'client_contact_edit',
    requestedBy: 'user2',
    requestedByName: 'Sarah Johnson',
    requestedAt: new Date('2025-10-12T11:20:00'),
    status: 'approved',
    reviewedBy: 'user3',
    reviewedAt: new Date('2025-10-12T14:30:00'),
    comments: 'Verified with client, approved',
    changes: [
      {
        field: 'title',
        oldValue: 'Chief Operations Officer',
        newValue: 'CEO',
      }
    ],
    resourceId: 'contact3',
  },
];

export const tasks: Task[] = [
  {
    id: 'task1',
    title: 'Prepare IT staffing proposal',
    description: 'Create detailed proposal for TechCorp Q1 2026 IT staffing needs',
    dueDate: new Date('2025-10-15T17:00:00'),
    priority: 'high',
    status: 'in_progress',
    ownerId: 'user1',
    ownerName: 'John Smith',
    assignedById: 'user3',
    assignedByName: 'Mike Wilson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    reminderEnabled: true,
    reminderDate: new Date('2025-10-15T09:00:00'),
    linkType: 'lead',
    linkId: 'lead1',
    createdAt: new Date('2025-10-13T10:30:00'),
    updatedAt: new Date('2025-10-13T10:30:00'),
    comments: [
      {
        id: 'comment1',
        taskId: 'task1',
        userId: 'user1',
        userName: 'John Smith',
        content: 'Started working on the proposal. Will have draft ready by tomorrow.',
        createdAt: new Date('2025-10-13T14:30:00'),
      }
    ],
  },
  {
    id: 'task2',
    title: 'Follow up with Healthcare Solutions',
    description: 'Check on nursing staff availability and schedule meeting',
    dueDate: new Date('2025-10-14T14:00:00'),
    priority: 'urgent',
    status: 'to_do',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    assignedById: 'user3',
    assignedByName: 'Mike Wilson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    reminderEnabled: true,
    reminderDate: new Date('2025-10-14T09:00:00'),
    linkType: 'lead',
    linkId: 'lead2',
    createdAt: new Date('2025-10-12T15:00:00'),
    updatedAt: new Date('2025-10-12T15:00:00'),
    comments: [],
  },
  {
    id: 'task3',
    title: 'Review warehouse proposal feedback',
    description: 'Manufacturing Global sent questions about the proposal',
    dueDate: new Date('2025-10-16T10:00:00'),
    priority: 'medium',
    status: 'to_do',
    ownerId: 'user1',
    ownerName: 'John Smith',
    assignedById: 'user3',
    assignedByName: 'Mike Wilson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    reminderEnabled: false,
    linkType: 'lead',
    linkId: 'lead3',
    createdAt: new Date('2025-10-10T16:00:00'),
    updatedAt: new Date('2025-10-10T16:00:00'),
    comments: [],
  },
  {
    id: 'task4',
    title: 'Send candidate profiles',
    description: 'Send accounting temp candidate profiles to Finance Partners',
    dueDate: new Date('2025-10-12T12:00:00'),
    priority: 'medium',
    status: 'done',
    ownerId: 'user4',
    ownerName: 'Emily Davis',
    assignedById: 'user4',
    assignedByName: 'Emily Davis',
    subCompanyId: 'sub2',
    subCompanyName: 'South Division',
    reminderEnabled: false,
    linkType: 'lead',
    linkId: 'lead4',
    createdAt: new Date('2025-10-08T11:30:00'),
    updatedAt: new Date('2025-10-12T11:00:00'),
    completedAt: new Date('2025-10-12T11:00:00'),
    comments: [
      {
        id: 'comment2',
        taskId: 'task4',
        userId: 'user4',
        userName: 'Emily Davis',
        content: 'Sent 5 candidate profiles. Client is reviewing.',
        createdAt: new Date('2025-10-12T11:15:00'),
      }
    ],
  },
  {
    id: 'task5',
    title: 'Update CRM with client notes',
    description: 'Add detailed notes from yesterday\'s client calls',
    dueDate: new Date('2025-10-13T18:00:00'),
    priority: 'low',
    status: 'done',
    ownerId: 'user1',
    ownerName: 'John Smith',
    assignedById: 'user1',
    assignedByName: 'John Smith',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    reminderEnabled: false,
    createdAt: new Date('2025-10-12T17:00:00'),
    updatedAt: new Date('2025-10-13T16:00:00'),
    completedAt: new Date('2025-10-13T16:00:00'),
    comments: [],
  },
  {
    id: 'task6',
    title: 'Prepare meeting agenda',
    description: 'Create agenda for IT staffing meeting with TechCorp',
    dueDate: new Date('2025-10-16T12:00:00'),
    priority: 'high',
    status: 'to_do',
    ownerId: 'user1',
    ownerName: 'John Smith',
    assignedById: 'user3',
    assignedByName: 'Mike Wilson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    reminderEnabled: true,
    reminderDate: new Date('2025-10-16T09:00:00'),
    linkType: 'meeting',
    linkId: 'meeting1',
    createdAt: new Date('2025-10-13T14:00:00'),
    updatedAt: new Date('2025-10-13T14:00:00'),
    comments: [],
  },
  {
    id: 'task7',
    title: 'Research retail staffing trends',
    description: 'Gather data for holiday season staffing proposal',
    dueDate: new Date('2025-10-17T17:00:00'),
    priority: 'medium',
    status: 'to_do',
    ownerId: 'user2',
    ownerName: 'Sarah Johnson',
    assignedById: 'user3',
    assignedByName: 'Mike Wilson',
    subCompanyId: 'sub1',
    subCompanyName: 'North Division',
    reminderEnabled: false,
    linkType: 'lead',
    linkId: 'lead5',
    createdAt: new Date('2025-10-13T10:00:00'),
    updatedAt: new Date('2025-10-13T10:00:00'),
    comments: [],
  },
];

export const leadRequests: LeadRequest[] = [
  {
    id: 'lr1',
    clientId: 'client6',
    clientName: 'Education Services Ltd',
    primaryContactName: 'Susan Miller',
    requestedBy: 'user1',
    requestedByName: 'John Smith',
    managerId: 'user3',
    managerName: 'Mike Wilson',
    note: 'I would like to request Education Services Ltd client. They have expressed interest in temporary teaching staff for the upcoming semester.',
    requestedAt: new Date('2025-10-12T09:30:00'),
    status: 'pending',
    comments: [
      {
        id: 'lrc1',
        userId: 'user1',
        userName: 'John Smith',
        text: 'I would like to request Education Services Ltd client. They have expressed interest in temporary teaching staff for the upcoming semester.',
        createdAt: new Date('2025-10-12T09:30:00'),
      }
    ],
    subCompanyId: 'sub1',
  },
  {
    id: 'lr2',
    clientId: 'client7',
    clientName: 'Construction Alliance Inc',
    primaryContactName: 'Tom Anderson',
    requestedBy: 'user1',
    requestedByName: 'John Smith',
    managerId: 'user3',
    managerName: 'Mike Wilson',
    note: 'I would like to request Construction Alliance Inc client. I have a strong existing relationship with Tom Anderson and believe we can secure a contract for skilled construction workers.',
    requestedAt: new Date('2025-10-10T14:20:00'),
    status: 'pending',
    comments: [
      {
        id: 'lrc2',
        userId: 'user1',
        userName: 'John Smith',
        text: 'I would like to request Construction Alliance Inc client. I have a strong existing relationship with Tom Anderson and believe we can secure a contract for skilled construction workers.',
        createdAt: new Date('2025-10-10T14:20:00'),
      },
      {
        id: 'lrc3',
        userId: 'user1',
        userName: 'John Smith',
        text: 'Just to add - Tom mentioned they have 3 new projects starting in November and will need at least 20-25 workers.',
        createdAt: new Date('2025-10-11T08:15:00'),
      }
    ],
    subCompanyId: 'sub1',
  },
  {
    id: 'lr3',
    clientId: 'client8',
    clientName: 'Logistics Express Co',
    primaryContactName: 'Maria Garcia',
    requestedBy: 'user1',
    requestedByName: 'John Smith',
    managerId: 'user3',
    managerName: 'Mike Wilson',
    note: 'I would like to request Logistics Express Co client. They need warehouse staff for peak season.',
    requestedAt: new Date('2025-10-08T11:00:00'),
    status: 'rejected',
    reviewedBy: 'user3',
    reviewedByName: 'Mike Wilson',
    reviewedAt: new Date('2025-10-09T10:30:00'),
    comments: [
      {
        id: 'lrc4',
        userId: 'user1',
        userName: 'John Smith',
        text: 'I would like to request Logistics Express Co client. They need warehouse staff for peak season.',
        createdAt: new Date('2025-10-08T11:00:00'),
      },
      {
        id: 'lrc5',
        userId: 'user3',
        userName: 'Mike Wilson',
        text: 'Unfortunately, I have to reject this request. Sarah Johnson has already been working with Logistics Express Co for the past 2 months and is close to closing a deal. We need to avoid duplicating efforts. Please coordinate with Sarah if you want to support this client.',
        createdAt: new Date('2025-10-09T10:30:00'),
      }
    ],
    subCompanyId: 'sub1',
  },
  {
    id: 'lr4',
    clientId: 'client6',
    clientName: 'Education Services Ltd',
    primaryContactName: 'Susan Miller',
    requestedBy: 'user2',
    requestedByName: 'Sarah Johnson',
    managerId: 'user3',
    managerName: 'Mike Wilson',
    note: 'I would like to request Education Services Ltd client. I have experience in education sector staffing and can handle their requirements effectively.',
    requestedAt: new Date('2025-10-05T15:45:00'),
    status: 'rejected',
    reviewedBy: 'user3',
    reviewedByName: 'Mike Wilson',
    reviewedAt: new Date('2025-10-06T09:00:00'),
    comments: [
      {
        id: 'lrc6',
        userId: 'user2',
        userName: 'Sarah Johnson',
        text: 'I would like to request Education Services Ltd client. I have experience in education sector staffing and can handle their requirements effectively.',
        createdAt: new Date('2025-10-05T15:45:00'),
      },
      {
        id: 'lrc7',
        userId: 'user3',
        userName: 'Mike Wilson',
        text: 'Rejecting this request as we need to focus your efforts on healthcare sector clients where you have the strongest track record. Education Services will be better served by a team member with more recent education sector experience.',
        createdAt: new Date('2025-10-06T09:00:00'),
      }
    ],
    subCompanyId: 'sub1',
  },
];
